title: Terraform Template
description: Generic template to create and setup an ATP Database and a Compute instance
stackDescription: Generic template to create and setup an ATP Database and a Compute instance
informationalText: Informational Text goes here
schemaVersion: 1.0.0
version: "20210113"
locale: "en"

variableGroups:
- title: Application
  visible: true  
  variables:
  - app_name
  
- title: General Configuration
  visible: false
  variables:
  - compartment_ocid
  - tenancy_ocid
  - region

- title: Compute
  visible: true  
  variables:
  - create_compute
  
- title: Compute Configuration
  visible: create_compute  
  variables:
  - instance_shape
  # - vcn_id
  # - subnet_id
  - keep_generated_ssh_key
  - ssh_public_key

- title: Database
  visible: true  
  variables:
  - create_database
  
- title: Database Configuration
  visible: create_database  
  variables:
  - admin_password

variables:
  app_name:
    title: Application Name
    description: This name will be used for your objects
    type: string
    required: true

  tenancy_ocid:
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    type: string
    required: true
    visible: false

# General Configuration - Not visible
  region:
    title: Region
    description: Region Name
    type: oci:identity:region:name
    required: true
    visible: false

  compartment_ocid:
    title: Compartment OCID
    description: Compartment OCID
    type: oci:identity:compartment:id
    required: true
    visible: false

# Required
  create_compute:
    title: Create a compute instance?
    description: Do you want to create the compute instance?
    type: boolean
    default: true
    required: true

  create_database:
    title: Create a database?
    description: Do you want to create the database?
    type: boolean
    default: true
    required: true

  admin_password:
    title: Database Admin Password
    description: Password must be 12 to 30 characters and contain at least one uppercase letter, one lowercase letter, and one number. The password cannot contain the double quote (") character or the username "admin". 
    type: oci:db:autonomous_database:admin_password
    required: true

  instance_shape:
    title: Instance Shape
    description: The shape for the compute instance
    type: oci:core:instanceshape:name
    default: VM.Standard.E2.1.Micro
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      
  # vcn_id:
  #   # prepopulates available values for VCN
  #   type: oci:core:vcn:id
  #   # determines values for VCN prepopulation from selected compartment
  #   dependsOn:
  #     compartmentId: ${compartment_ocid}
 
  # subnet_id:
  #   # prepopulates available values for subnet
  #   type: oci:core:subnet:id
  #   # determines values for subnet prepopulation from selected compartment and VCN
  #   dependsOn:
  #     compartmentId: ${compartment_ocid}
  #     vcnId: ${vcn_id}
  
  keep_generated_ssh_key:
    title: Keep Generated SSH Key
    description: An SSH key-pair is generated in order to configure the compute instance.  It is not safe to use this key for production systems because the private key is stored in terraform state file and can be viewed by anyone who has access to the stack.  Uncheck this box if you want this key to be removed from the authorized key list on the compute instance at the end of the setup process.  Check this box if you want to display and use this key.
    type: boolean
    default: false
    required: true

  ssh_public_key:
    title: SSH Public Key
    description: The public SSH key for the key-pair that you want to use to login to instances via SSH.
    type: oci:core:ssh:publickey
    required:
      not:
        - keep_generated_ssh_key
    additionalProps:
      allowMultiple: true
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"

outputGroups:
  - title: ${Messages.solutionsHub.solutions.ociDevTools.outputGroups.title()}
    outputs:
      - compute_instance_public_ip
      - compartment_id
      - generated_instance_ssh_private_key
      - db_wallet_password

outputs:
  compute_instance_public_ip:
    title: Compute Instance Public IP
    displayText: Compute Instance Public IP
    type: copyableString
    visible: true

  compartment_id:
    title: Compartment Id
    displayText: Compartment OCID
    type: string
    visible: true
  
  generated_instance_ssh_private_key:
    title: Generated Private Key for SSH Access
    displayText: Only shown if it has not been removed from the compute instance authorized keys.
    type: string
    visible: true
  
  db_wallet_password:
    title: Database Wallet Password
    displayText: Password for the Database Wallet .zip file
    type: copyableString
    visible: true

